local M = {}

M.ui = {
	ArrowLeft = "",
	ArrowRight = "",
	Check = "✓",
	Fire = "",
	Gear = "",
	History = "",
	List = "",
	Lock = "",
	Circle = "",
	BigCircle = "",
	BigUnfilledCircle = "",
	Close = "",
	NewFile = "",
	Search = "",
	Lightbulb = "",
	Project = "",
	Dashboard = "",
	History = "",
	Comment = "",
	Bug = "",
	Code = "",
	Telescope = "",
	Gear = "",
	Package = "",
	List = "",
	SignIn = "",
	SignOut = "",
	Tab = "",
	File = "",
	Files = "",
	Folder = "",
	FolderOpen = "",
	FolderClosed = "",
	DapBreakpoint = "",
	DapLogPoint = "",
	DapStopped = "",
	DefaultFile = "",
	Symlink = "",
	FolderEmpty = "",
	FolderSymlink = "",
	BookMark = "",
	Pencil = "",
	ChevronRight = "",
	Table = "",
	Calendar = "",
	CloudDownload = "",
}

M.diagnostics = {
	Error = "",
	Warning = "",
	Information = "",
	Question = "",
	Hint = "",
}

M.git = {
	LineAdded = "",
	LineModified = "",
	LineRemoved = "",
	FileDeleted = "",
	FileIgnored = "◌",
	FileRenamed = "",
	FileStaged = "S",
	FileUnmerged = "",
	FileUnstaged = "",
	FileUntracked = "U",
	Diff = "",
	Repo = "",
	Octoface = "",
	Branch = "",
}

M.lsp = {
	Array = "",
	Boolean = "",
	Class = "",
	Color = "",
	Constant = "",
	Constructor = "",
	Enum = "",
	EnumMember = "",
	Event = "",
	Field = "",
	File = "",
	Folder = "",
	Function = "",
	Interface = "",
	Key = "",
	Keyword = "",
	Method = "",
	Module = "",
	Namespace = "",
	Null = "NULL",
	Number = "",
	Object = "",
	Operator = "",
	Package = "",
	Property = "",
	Reference = "",
	Snippet = "",
	String = "",
	Struct = "",
	Text = "",
	TypeParameter = "",
	Unit = "",
	Value = "",
	Variable = "",
}

M.misc = {
	Robot = "ﮧ",
	Squirrel = "",
	Tag = "",
	Watch = "",
	Smiley = "",
	Package = "",
	CircuitBoard = "",
}

return M