#!/usr/bin/env bash

set -euo pipefail

echo "Installing Fast Node Manager (fnm)..."
brew install fnm

# Add fnm to shell
echo "Configuring fnm..."
eval "$(fnm env --use-on-cd)"

echo "✅ Node.js setup completed"
