#!/usr/bin/env bash

set -euo pipefail

echo "Installing tools..."

brew install --cask ghostty syncthing obsidian raycast
brew install git git-delta ripgrep jq fzf k9s sqlc figlet bat ranger curl lazygit tailscale tmux starship

echo "✅ Tools installation completed"
exit 0
