#!/usr/bin/env bash

set -euo pipefail

echo "Installing tools..."

brew install --cask ghostty syncthing obsidian raycast cameracontroller
brew install git git-delta ripgrep jq fzf k9s sqlc figlet bat ranger curl lazygit tailscale tmux starship tree protobuf awscli

echo "Installing language servers..."
brew install lua-language-server typescript-language-server pyright gopls rust-analyzer

echo "✅ Tools installation completed"
exit 0
