#!/usr/bin/env bash
if [ ! -d $HOME/repos/github.com/lukeberry99/dev ]; then
    mkdir -p $HOME/repos/github.com/lukeberry99/dev
fi

git clone https://github.com/lukeberry99/dev $HOME/repos/github.com/lukeberry99/dev

pushd $HOME/repos/github.com/lukeberry99/dev
./install
./configure
popd
